console.log("Let's build a pyramid using JavaScript basics");
console.log("    #    ");
console.log("   ###   ");
console.log("  #####  ");
console.log(" ####### ");
console.log("#########");
let character = "'Hello'";
console.log(character);
character = "'World'";
console.log(character);
